/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XmelisekAmbulanceEquipList {
    }
    interface XmelisekAmbulanceMenu {
    }
    interface XmelisekAmbulanceOrderList {
    }
}
declare global {
    interface HTMLXmelisekAmbulanceEquipListElement extends Components.XmelisekAmbulanceEquipList, HTMLStencilElement {
    }
    var HTMLXmelisekAmbulanceEquipListElement: {
        prototype: HTMLXmelisekAmbulanceEquipListElement;
        new (): HTMLXmelisekAmbulanceEquipListElement;
    };
    interface HTMLXmelisekAmbulanceMenuElement extends Components.XmelisekAmbulanceMenu, HTMLStencilElement {
    }
    var HTMLXmelisekAmbulanceMenuElement: {
        prototype: HTMLXmelisekAmbulanceMenuElement;
        new (): HTMLXmelisekAmbulanceMenuElement;
    };
    interface HTMLXmelisekAmbulanceOrderListElement extends Components.XmelisekAmbulanceOrderList, HTMLStencilElement {
    }
    var HTMLXmelisekAmbulanceOrderListElement: {
        prototype: HTMLXmelisekAmbulanceOrderListElement;
        new (): HTMLXmelisekAmbulanceOrderListElement;
    };
    interface HTMLElementTagNameMap {
        "xmelisek-ambulance-equip-list": HTMLXmelisekAmbulanceEquipListElement;
        "xmelisek-ambulance-menu": HTMLXmelisekAmbulanceMenuElement;
        "xmelisek-ambulance-order-list": HTMLXmelisekAmbulanceOrderListElement;
    }
}
declare namespace LocalJSX {
    interface XmelisekAmbulanceEquipList {
    }
    interface XmelisekAmbulanceMenu {
    }
    interface XmelisekAmbulanceOrderList {
    }
    interface IntrinsicElements {
        "xmelisek-ambulance-equip-list": XmelisekAmbulanceEquipList;
        "xmelisek-ambulance-menu": XmelisekAmbulanceMenu;
        "xmelisek-ambulance-order-list": XmelisekAmbulanceOrderList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xmelisek-ambulance-equip-list": LocalJSX.XmelisekAmbulanceEquipList & JSXBase.HTMLAttributes<HTMLXmelisekAmbulanceEquipListElement>;
            "xmelisek-ambulance-menu": LocalJSX.XmelisekAmbulanceMenu & JSXBase.HTMLAttributes<HTMLXmelisekAmbulanceMenuElement>;
            "xmelisek-ambulance-order-list": LocalJSX.XmelisekAmbulanceOrderList & JSXBase.HTMLAttributes<HTMLXmelisekAmbulanceOrderListElement>;
        }
    }
}
